# Generated by Django 3.0.8 on 2020-07-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_newsletterrecipient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletterrecipient',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
